# Generated by Django 4.1.3 on 2023-05-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id_book', 'data']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='id_book',
        ),
    ]
