# Generated by Django 4.1.3 on 2023-06-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_author_genre_lenguage_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AddField(
            model_name='author',
            name='id_book',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_book_author', to='API.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_book',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_book',
            field=models.CharField(max_length=100),
        ),
    ]
