# Generated by Django 4.1.3 on 2023-06-07 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_book_options_author_id_book_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name_author', 'date_of_birth', 'date_of_death', 'id_book']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id_book', 'title_book', 'description', 'isbn_book']},
        ),
        migrations.AlterField(
            model_name='author',
            name='id_book',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_book_author', to='API.book'),
        ),
    ]
